on: [push, pull_request]
name: Test
jobs:
  tests:
    strategy:
      matrix:
        go-version: [ 1.23.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    services:
      nats-streaming:
        image: nats-streaming:0.25.6
        ports:
          - "4223:4222"
          - "8223:8222"

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make tests
