on: [push, pull_request]
name: Test
jobs:
  tests:
    strategy:
      matrix:
        go-version: [ 1.23.x ]
    runs-on: [ self-hosted ]
    services:
      nats-streaming:
        image: nats-streaming:0.25.6
        ports:
          - "4223:4222"
          - "8223:8222"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -timeout 30s -race -short `go list ./... | grep -v mocks`
